---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-postgres-secret
  namespace: airflow
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA5c0RsGqM1qqcWSuPxy6gvulTVcERN8DP64str/XWbnHp4LxfZIY8tgEODWU5AH+KgFNijzcQHxtXeks2cxTALniFDG76Vp/eEAbFZWwHwH1eHez6thBREMRvbNyiWGkYZKMD4HIC0leeNM/tsnnCE1Yv6TlNHGhbtYTcLDgge63iuhcXc4y/mnbxucx1XGNsS67FWTLG9L9IgLS66AJpfntbS45f+f3a2NU5R5ESVF5vr5oidCipEFzX9UAhuWxk7G5nfigHt04kA3ElLtENNYAIagUhjn8yxchP1YSAlWuwktyd6R9THY8D+J6k527wK+jCRGuT5H0/ghBSAkTv6Tl9MJ22kTXC+kHjrloZ/nce+jSe21vxvC0e0wy8YWlihBm3YzysCwxRkdTndfy6dbW4bUrNx3veIBEWVzVvowvbYcIKMhnhMKRCkGr4dqrn+tDlHqhQzXZUuBOvn3V8l3htyntOrATGF3NdCllrajduFNz64w3RpP2GPlpyqXUswmKk85AnmfLKJ5xnDauGJLjvVc8vnaEpfWIZsqvohsgfl6j8LtHzon6WuGPh5kQWzLtE2CSTHMlhehW3zNvq2Km14XRk+0SZJwguEj6URiwBL9gg8d/w5jT3rGKWqXmLK4+a3LHs4L//Nu/ih3LOstX/nhkoKSQvRm9YxcR1XSItHn260PqOzttC8vJ9+3J8oq4hn/wQ0
  template:
    metadata:
      name: airflow-postgres-secret
      namespace: airflow
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-metadata-secret
  namespace: airflow
spec:
  encryptedData:
    connection: AgBFWr4QQGn1xmejqOsHqTDEANum+x1qFeRCMs+fZ7g3ZKdisqQzcATziGC9eTxSAtN3pInkfAoFVN49/2O3w9MCbBBLousw+qsIfd2tBAtLTYYhdwJPB9BXQH4Ad4BstT869x3l6PCq6fl2WNE7AaCq4JwbkyhlrJzW8ndA2ruyEgG1gblQafcU/Ba5qm3RSKmUI2QeToMkVQOvlkrt5W8JGUABSbGdeJlT/RoOSDWuoUsn/yBcK61eShJXNjQun/ot60wwuE8g3bJmni5QXnd2EQH0vKyFYc2Rs1VZFcVbWhJ5rTH5MQFpIOfTzUQkealgbcNAPKDv2zLnpUtH/5DyURkwLC84SCY/ssf0HS72130SMyGxJhDxoSOKL7YvukOmYDQOcTxymR7snf4kHm1/fWmtE2HUyfQQp+M55EqTY9/t8W4HU/oDrLTpuFLMalXUnKVAU5wNJWK3slPSixx4BpDmzbG7mAno/E3NYxm7kiz1U82D+PIN5ASVTGUAAf2Q4L3y/HRiRNDLQLkMK+wJq9K1eGWP4lsxRk/TxUeJpe8gluEvbl3Mve+iq0CjQ+lA2hxKScUcLrRX+8+tmDWgoflSY22tfzGUxbadEuHpoQ21p6aFWUmrWZ9Adqti2DmwugNu/mLe0hHU0N1imPlXO4vLdwGXJaKw9SVOKY0HK65BRILwsT814xn3J3i0vyTA9r0zJ8bDJ/4upvXGHyDSOSGMsFL1PZDXBT6vgqJvpB3LH6b03PC5wH7OS2NsSnw6c0aNDKugZMVDZMXukYrumJFI
  template:
    metadata:
      name: airflow-metadata-secret
      namespace: airflow
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-admin-secret
  namespace: airflow
spec:
  encryptedData:
    airflow-admin-password: AgCCUdnygISkrEm1uzf+uUzmBkQAvb1VLmIohB7ExxNqh0QP903A7jmlWTF3MrlIkrhD+avRmNAreFvgEdMHb1LlonID5goDNxFKSa79VDVNaMI9cn7rRW08KEtc+y3KTS8nVe2l1LhRzEnB8k0HvJJ/Pz6b51SE1XD6xmvA8dr5m5Q9jBsT6RgZljoe8X5MzODfTPVEpC9+L0gKI0uqM5BMp3kidnXDopMBTzhUSqwDBMN1naDd+OIvEeSog9fRP2XwypF0L9v6F9/6qi8A2h4ghlzIz2zRrtawlRxlQpMbOj8F1KFK6r3ndj9kZWmjaqaGllfGuDR+D8tO+eBO15CEz5aJ9Q3ehvh5/u4GdVyzo5GGwvnEeuvin40pBYpawwAASDGaLwp2Hk7TRiy/OTKel0RA5jrONu3SkbSmysIBSKOB0zv6H2HUskI/WXoj+jGZuzhup3ZmxwCi0yXO2GCvGjP1PhBlRIVDALZuRBPh7Cv+nSXToEbtSsBue67VTWtCznnTiseKtv+PawOvovXKqUIdGlQPmgnPsITzzlCdflPRdEOCW6aUrSd/pgNa9+i9Te06eEZc3IdVo7ZYZBJ+E4Xq4oMTCOwvhTJOPdF7xFvmFZDzCM1QzzH65Hu16R/Ic1jSdzKijQhhk/SfKE0VDNs9JSmCm13xNqArFp0123vOxd+8VpH7N1XW2u2UZ9mSuenXEg==
  template:
    metadata:
      name: airflow-admin-secret
      namespace: airflow
    type: Opaque
