---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-postgres-secret
  namespace: airflow
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAahOa1IxJQ5PBoBG4mZK/TKDdqPZ/qeelhlXMVTceOfCzOQzLWCtTdSc4+VHbQ0lgOBMYFf5a69IUTg52ebEU6M5Ib/8lIVobDPNNKxlpC/5/A1dgdNBMokQJG+q2bo6vvTDyLnGLplO+KLyRgmU6rJBjcj+zcP0UbIwX+W12PhwdmhLLuA3YbA4D6iZkTtkXyQ9cAOou0abCnwoBBG/lDGW2DTUufN+h/r5Zijnctf/zYXcokM35nqCdT78kn7o4eU3PFPSvyK5hu0Ofec42k9vD/3Xq7aBAVSyL7B4ustICK/2AD75/kxzjOcu56hTNsrtU0ga53NLRQq1P1s3Z/9iWA6meeCymRpGUI3n7B3wKMMotvxb9QFkqPzkzwebaupvc9O23TI0tWJXFObl+bm2HoatbNSVlM/ZVbYlptRe2AhSq376a9eifD5vSettpJBKOUQqNTY9XNL4hWeAVqnWJVBBHtT8EAOhFidFveNfrSt66pid4IFMlBqi2aiRT44MjWp7GUOi4xapyoKUUbSjHJlHwrYnPzslwOxfDlbc4wG3FCb++nVw5C1QSgZiUi3KqGvygfPBQgu2JN4kqJ+8717TOAgLm4VftGYhpBb1IeIi9/l87bghgf7Aka2tgp7kPecEJoNkcp1t1ayO5Jxvv6AN5AHmSVJrBnIboMOAuCGG4RwaBcAQswO6Zi1CQh7Kh4SkbT
  template:
    metadata:
      name: airflow-postgres-secret
      namespace: airflow
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-metadata-secret
  namespace: airflow
spec:
  encryptedData:
    connection: AgAUDMcTmZNzqg8f539P71OO5sPyizXP5NdXawDGLtxU2JTamfOP29hj+T8xNmLNE2ZnMRsmALFGHbKZBY6dYaqR95aGsqjsVPyn/jKNqhBhnoVfFnjZ63r5LOkcu6WeMFA/T40BcwrToBYE4BYTAGxsnFLDL0PTYDR4MNfrX1gvST4MtY8G5Cz9FyPfQGZsjIQyfeGD9iWH8zikuFoIktZvu7h0smkzE6DjuruH7UjvmriqvrzGhSvm1L0XeBdOz+uqdYSL+l6OVxElPkYVAnzp6c4xywxGakxgc1Eh05L1bZ1ws+txt6X8iH0n4p9WJOGYfVbEkoog0SbZuJ9esAlHsqf7soobwuyqWQ8ZEcZlVWZiehMfdE5IsQ+pvLDpXwxn2qfaouYYLtLUv26MlvshU5Rgx/IqvY2a+oUC8cGW858L3Mbwp+J7shv1WXxM2K5JyOs6KHP2oLyfDc9gHKQ1FVLpoOfktj9sJT9SyP2WYeQ64gKh4Jr8X28T/IF5Y06BWu/ipuMfBi96Rn8P4v8OiLLtXrrEw23a+TG8lbIaYT1Z8e+DD0+c3fFmFLm/my7SX8sYRoZxqVHusUmSDTakLqbWNNEA6FzMRGYE+HawXlifCo8JV/m1DhGfzB8rrMQ/rek46hRLnsmooCNvxb7bgktvPqPW5q+0ptudhIvamKVlIba4VHnWInouKy0WH0ZNCDpkN3LN5qWzfBajCbArcogVrxDdZP70jwtYurHT2IrKk6dBwdVDJ3a8LLPnMmOCxJB8ATX8Du+m0dHR52T8be8e
  template:
    metadata:
      name: airflow-metadata-secret
      namespace: airflow
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-admin-secret
  namespace: airflow
spec:
  encryptedData:
    airflow-admin-password: AgC3AENnb5bV/5hEbKz65VV3WNIpc8sZYBKr0fCn2hlTslUkQAbJMKsMR4EGXInFJV0UMxz53ighWFVLqsRP6COPuQ48PWVjmYAC1BeVH345Y/nOtJl2BRYqQJRQFFYWCFS3tdAkQb0BrMv4+7AUmyGL3gkpbEt05RuWBod3ZAJyDSyRqqsmgaf5pL3yAHN66GDsJlQVSbUnsGtO9ahNZw96HpdECMd7suOV5ffOg0lO+m1tIFrbzzv6VZgn8gs0DqXk6HT1T+UkhLWFtKZI/s6KgA8Z2dWsr6Gn7MDplHls9i3gzbxWq6zbQIqimKRGp8m4t3UHKHP2+irMhTXTS2xtD2qWIHEvZo1Jvm9XUO0y1AL89ZfsAc9oJkeqR3TC7x+zczjcUjCnJ6ZQaAb+BjIbYiJl/LuGlYlCOFqTtB4NVY7GAfS2F5ddz66G/oc1FJisgghyvbRIAzOLOJOSWLJ38SAByoPJ4S2dRlCaD1cL8ZAj5cpVwGKSiVQA//vUi65IA5KcUanqGHIM8IEK17iQJ4sXIrKg/N/EvbqSQlaC1c2zhQScz1wiq8vgSNOZU2aa6qvC5cnJsPpSr9rs0uQHsCjSpmiyyJYJsw6VvvbcQhRM4lP9M1R0eWUn5mBIpsTQEaRhoRR1Ax1s4xwG1uULTCESVWuqtOIXr5hkkHy5JX5V5TJ+ChD5v4VaLSk2LuHCImAmXw==
  template:
    metadata:
      name: airflow-admin-secret
      namespace: airflow
    type: Opaque
