---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-postgres-secret
  namespace: airflow
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAuczvE3/jJY8vzy+y8qLlkeJ1r74cVno+ShORHZCf1zzXsOhmWFaAJtZd1fhNB7ZoymfU28vlYG1/mi0Htd8ZeIyxclXfvz2FoZrgfJPj5Y7or5M4ZGkKX+wkwAxsguUhF0b0ZSY4oFoDWei9qc2U1YO1V5iU7s58odKhSdeXrICrW/YqG0v0Db85Dgf2/i7A4LqWIh75Otzj6cPwHChTOddlnw6O/1eiWV71r4Pw9oai5Ys1JpgXBxYdDpn+WVAONZX+fgQhGjDjoSY4qcOaSDzP15bQZ23K6UHo668wBfL5ITCA1YC+rlr0fhIfeUoulRlSSE437bAdncjxmt9V/j61yZm0yt6U0GMe5tkL9k6dxLTp9F6+xd1ggcbkOUayEODQf4wpVUmzW/QOurhNrhI9uRr+aMgR0TRZeo4+duOmioFpa5vna86IcHWTHwPB9QNqPQaW4Y8/yLyAr0T6ZV9uZJPxXop5DKkMl0KcrrclphCnHi/o24E26u8VW32tMugwnl3X+pBrGbgwGdFbqJnLobNfzsN5TjJjG1P7kgEVoMvcuxdUIaiSuGHbME612Op4YtZGprrJIB4ziIzwMf9TA1wqIWPBU4F/JAOAQMBNksw+lMCigI3S6gCDDkqx6Kc8bj1fA3uCTOdPZTRlY0Nee287ZcMJioTDyTanHkQT1VYqqhLmppToHbVrUh1TAK7gBerQK
  template:
    metadata:
      name: airflow-postgres-secret
      namespace: airflow
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-metadata-secret
  namespace: airflow
spec:
  encryptedData:
    connection: AgAAlveg8or7VAMRVf/MTPXQrTq8Xi6T4yvmkgnLgfeR3X2piB9xE+xNMixvJWnysB7w6j7CxAkDjFo/tZBDrG0dhk6WwF7rXU0AnUke0lGtKhoWFYdQ6kxwD0DtPm1lAi8v0thT8aclaNWYe3uoSMCv3vBzmon8nI7KGmW9npmInsbnb790UvdRVNrpmdBb9qBRwiM50s7z6KPlSNNswiYnWaoLMYVgTmCSH2YKNQfSzFYRlgTlDG9ElJ+aOzjUZlV657fBj+rAHBwEdG/CVsKTecVb8H2MdYG/SfDBQNq7loo3gUN2sREFvVpHIKFeqeGxvoVDYuSOl16G9WshVcrhqppoZw/EJDxUTqDMuApnZrVUG32LPh80S3dUN/RL48Va9x3nHjTJ9ioL6lkf+aHlgREhIgnLcxCXXRk6YH7IR82bZ3ES8lZNjfc7goQaor07G9oBTZmx9tVJmark4FbuHLbFNDc51KyyZ9Ns5yxva2I5yTP35Mo1PSC+diJb1PjkXJKMGqmAsp86Q+IS+8/fr90CXZUfxqHsS128Ij8X4fhbKOBOzwz+/jHE8ckGLot6t9Z/7xx4p2q8aZnj2henj1hxo1ST2JTnparoVe7uaXTmo1PjT+w9dPxUuCiFPOPVtiRVy5DTVQQN7UJqvpwRNvqqg51yGIG/e16jIzyQrkb6lTA9S00Sw1fHAnemMzh9QWWGxxRe8OGqdw4qfiffJ0DeTzQSBJNXQmI5AGJgsIUrmjDw+omrVETZGzpl4tmxqXBX02YFnMqVzGzmtcbY5D+F
  template:
    metadata:
      name: airflow-metadata-secret
      namespace: airflow
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-admin-secret
  namespace: airflow
spec:
  encryptedData:
    airflow-admin-password: AgAZuApnws5buwZ+Zg/Ui68aBeD5rc176wgD0VXWkBnD56OI6v45iIxvf3A3E0D41FlJmZr0eiWDJnpMDE/BLr0siCXrf8rj1CHI35w9R+2hgv2aK9LZbg+4sI7dqxfjc9u0UDKextE7J9CJZDi8dkcRf2Jg4gJkRFODG6SKVbb6xm/o7KSF1Xluv128UQze6uMbOPsnbKl3sqZr/o90bujAm2fU60mPpkMWIz1183z2FbQh+MierLYs3GGBdamh6YXKEfPRpHv1bT3ehyBvI/MM9iDRORKSoDXTaiJchKQDEAtFWgkxjImjyb4Zc+Gmsuw8opGDx0iL+g0V8m6UhLwQMFSqE2IDiI39rqtc+ra9TB2u3ASEq6vuHE6xHw5dsPf8z1hTXkKaPN3j4z/6FDOk+vu+GMe35Eu0iAq6ptIjo1RpO6hbNQKDGueS3yfwGqmyBngQkQY2dEN8pBuVu3trd2NhaTw1H5o4l4yfRercvooWXFqy1IjigSAYJ8KEq3wdGwr8HD+mIwA51XPLxbdG1US1APXPFwm0s2Lr0dByQKGJIuElxVmjOOCvAbMGv7EVZlXySg5uCoQaEzEkSXSPnvG/BvG9d1uSdIqhs2CcPlc206xDXEF7w3NEvhSqlG1gHIrumHEY7nRVRLZCPP2QwqIOii/UT9k+sO1xw2TpoB7Fnhqfwl2k+AU1mLjrGDxavBFg9A==
  template:
    metadata:
      name: airflow-admin-secret
      namespace: airflow
    type: Opaque
